[project]
name = "pdr-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "pdrtpy",
]

[tool.uv.sources]
pdrtpy = { path = "../pdrtpy", editable = true }
